name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      artifact-metadata: write
      attestations: write
      id-token: write
      packages: write

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: Lavalink.jar

      - name: Upload Artifacts to GitHub Release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          TO_APPEND: |-


            Artifact attestation available at:
            ${{ needs.build.outputs.attestation_url }}
        run: |
          gh release upload "$RELEASE_TAG_NAME" Lavalink.jar
          notes=$(gh release view "$RELEASE_TAG_NAME" --json body -q .body)
          gh release edit "$RELEASE_TAG_NAME" --notes "${notes}${TO_APPEND}"
