name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      packages: write

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          name: Lavalink.jar

      - name: Upload Artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: Lavalink.jar
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
